openapi: 3.2.0
info:
  title: LilyApp API - Nest Based Application Metrics API
  description: Lily App Middleware
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Metrics
paths:
  /metrics:
    get:
      operationId: PrometheusController_index
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - Metrics
      summary: Prometheus controller index
      x-summary-source: derived
components:
  securitySchemes:
    JWT:
      scheme: bearer
      bearerFormat: JWT
      type: http
      in: header
