openapi: 3.2.0
info:
  title: LilyApp API - Nest Based Application LilyApp API Nest Based…
  description: Lily App Middleware
  version: '1.0'
  contact: {}
servers: []
tags:
- name: LilyApp API Nest Based Application
paths:
  /:
    get:
      operationId: HomeController_healthCheckRoot
      parameters: []
      responses:
        '200':
          description: ''
      tags:
      - LilyApp API Nest Based Application
      summary: Home controller health check root
      x-summary-source: derived
components:
  securitySchemes:
    JWT:
      scheme: bearer
      bearerFormat: JWT
      type: http
      in: header
