openapi: 3.2.0
info:
  title: LilyApp API - Nest Based Application Batch API
  description: Lily App Middleware
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Batch
paths:
  /batch/ingestions/{subsidiaryId}:
    get:
      operationId: BatchController_listAllBatches
      parameters:
      - name: subsidiaryId
        required: true
        in: path
        schema:
          type: number
      responses:
        '200':
          description: Get batches for subsidiary
      security:
      - JWT: []
      tags:
      - Batch
      summary: Batch controller list all batches
      x-summary-source: derived
components:
  securitySchemes:
    JWT:
      scheme: bearer
      bearerFormat: JWT
      type: http
      in: header
