openapi: 3.2.0
info:
  title: LilyApp API - Nest Based Application Enrichment Platform…
  description: Lily App Middleware
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Enrichment Platform Proxy
paths:
  /ep-proxy/*:
    get:
      operationId: EnrichmentPlatformProxyController_proxy_get
      parameters:
      - name: x-subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Enrichment Platform Proxy
      security:
      - JWT: []
      summary: Enrichment platform proxy controller proxy get
      x-summary-source: derived
    post:
      operationId: EnrichmentPlatformProxyController_proxy_post
      parameters:
      - name: x-subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Enrichment Platform Proxy
      security:
      - JWT: []
      summary: Enrichment platform proxy controller proxy post
      x-summary-source: derived
    put:
      operationId: EnrichmentPlatformProxyController_proxy_put
      parameters:
      - name: x-subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Enrichment Platform Proxy
      security:
      - JWT: []
      summary: Enrichment platform proxy controller proxy put
      x-summary-source: derived
    delete:
      operationId: EnrichmentPlatformProxyController_proxy_delete
      parameters:
      - name: x-subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Enrichment Platform Proxy
      security:
      - JWT: []
      summary: Enrichment platform proxy controller proxy delete
      x-summary-source: derived
    patch:
      operationId: EnrichmentPlatformProxyController_proxy_patch
      parameters:
      - name: x-subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Enrichment Platform Proxy
      security:
      - JWT: []
      summary: Enrichment platform proxy controller proxy patch
      x-summary-source: derived
    options:
      operationId: EnrichmentPlatformProxyController_proxy_options
      parameters:
      - name: x-subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Enrichment Platform Proxy
      security:
      - JWT: []
      summary: Enrichment platform proxy controller proxy options
      x-summary-source: derived
    head:
      operationId: EnrichmentPlatformProxyController_proxy_head
      parameters:
      - name: x-subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      tags:
      - Enrichment Platform Proxy
      security:
      - JWT: []
      summary: Enrichment platform proxy controller proxy head
      x-summary-source: derived
components:
  securitySchemes:
    JWT:
      scheme: bearer
      bearerFormat: JWT
      type: http
      in: header
