openapi: 3.2.0
info:
  title: LilyApp API - Nest Based Application Pi Api Proxy API
  description: Lily App Middleware
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Pi Api Proxy
paths:
  /pi-api-proxy/*:
    get:
      operationId: PiApiProxyController_proxy_get
      parameters:
      - name: subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Api Proxy
      summary: Pi api proxy controller proxy get
      x-summary-source: derived
    post:
      operationId: PiApiProxyController_proxy_post
      parameters:
      - name: subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Api Proxy
      summary: Pi api proxy controller proxy post
      x-summary-source: derived
    put:
      operationId: PiApiProxyController_proxy_put
      parameters:
      - name: subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Api Proxy
      summary: Pi api proxy controller proxy put
      x-summary-source: derived
    delete:
      operationId: PiApiProxyController_proxy_delete
      parameters:
      - name: subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Api Proxy
      summary: Pi api proxy controller proxy delete
      x-summary-source: derived
    patch:
      operationId: PiApiProxyController_proxy_patch
      parameters:
      - name: subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Api Proxy
      summary: Pi api proxy controller proxy patch
      x-summary-source: derived
    options:
      operationId: PiApiProxyController_proxy_options
      parameters:
      - name: subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Api Proxy
      summary: Pi api proxy controller proxy options
      x-summary-source: derived
    head:
      operationId: PiApiProxyController_proxy_head
      parameters:
      - name: subsidiary-id
        required: true
        in: header
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Api Proxy
      summary: Pi api proxy controller proxy head
      x-summary-source: derived
components:
  securitySchemes:
    JWT:
      scheme: bearer
      bearerFormat: JWT
      type: http
      in: header
