openapi: 3.2.0
info:
  title: LilyApp API - Nest Based Application Pi Config Proxy API
  description: Lily App Middleware
  version: '1.0'
  contact: {}
servers: []
tags:
- name: Pi Config Proxy
paths:
  /pi-config-proxy/*:
    get:
      operationId: PiConfigProxyController_proxy_get
      parameters: []
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Config Proxy
      summary: Pi config proxy controller proxy get
      x-summary-source: derived
    post:
      operationId: PiConfigProxyController_proxy_post
      parameters: []
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Config Proxy
      summary: Pi config proxy controller proxy post
      x-summary-source: derived
    put:
      operationId: PiConfigProxyController_proxy_put
      parameters: []
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Config Proxy
      summary: Pi config proxy controller proxy put
      x-summary-source: derived
    delete:
      operationId: PiConfigProxyController_proxy_delete
      parameters: []
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Config Proxy
      summary: Pi config proxy controller proxy delete
      x-summary-source: derived
    patch:
      operationId: PiConfigProxyController_proxy_patch
      parameters: []
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Config Proxy
      summary: Pi config proxy controller proxy patch
      x-summary-source: derived
    options:
      operationId: PiConfigProxyController_proxy_options
      parameters: []
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Config Proxy
      summary: Pi config proxy controller proxy options
      x-summary-source: derived
    head:
      operationId: PiConfigProxyController_proxy_head
      parameters: []
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - Pi Config Proxy
      summary: Pi config proxy controller proxy head
      x-summary-source: derived
components:
  securitySchemes:
    JWT:
      scheme: bearer
      bearerFormat: JWT
      type: http
      in: header
