openapi: 3.2.0
info:
  title: LilyApp API - Nest Based Application Faqs API
  description: Lily App Middleware
  version: '1.0'
  contact: {}
servers: []
tags:
- name: FAQs
paths:
  /faqs/{skuId}:
    get:
      operationId: FaqProxyController_proxy_get
      parameters:
      - name: skuId
        required: true
        in: path
        description: SKU ID
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - FAQs
      summary: Faq proxy controller proxy get
      x-summary-source: derived
    post:
      operationId: FaqProxyController_proxy_post
      parameters:
      - name: skuId
        required: true
        in: path
        description: SKU ID
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - FAQs
      summary: Faq proxy controller proxy post
      x-summary-source: derived
    put:
      operationId: FaqProxyController_proxy_put
      parameters:
      - name: skuId
        required: true
        in: path
        description: SKU ID
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - FAQs
      summary: Faq proxy controller proxy put
      x-summary-source: derived
    delete:
      operationId: FaqProxyController_proxy_delete
      parameters:
      - name: skuId
        required: true
        in: path
        description: SKU ID
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - FAQs
      summary: Faq proxy controller proxy delete
      x-summary-source: derived
    patch:
      operationId: FaqProxyController_proxy_patch
      parameters:
      - name: skuId
        required: true
        in: path
        description: SKU ID
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - FAQs
      summary: Faq proxy controller proxy patch
      x-summary-source: derived
    options:
      operationId: FaqProxyController_proxy_options
      parameters:
      - name: skuId
        required: true
        in: path
        description: SKU ID
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - FAQs
      summary: Faq proxy controller proxy options
      x-summary-source: derived
    head:
      operationId: FaqProxyController_proxy_head
      parameters:
      - name: skuId
        required: true
        in: path
        description: SKU ID
        schema:
          type: string
      responses:
        '200':
          description: ''
      security:
      - JWT: []
      tags:
      - FAQs
      summary: Faq proxy controller proxy head
      x-summary-source: derived
components:
  securitySchemes:
    JWT:
      scheme: bearer
      bearerFormat: JWT
      type: http
      in: header
